- backend/mars-interpreter/src/main/kotlin/internal/instruction/Jump.kt
- backend/mars-interpreter/src/test/kotlin/instruction/TestJump.kt
New branch for cleaner history
Closes #63
>  [#63] Implement Jump instruction

- backend/shork/src/main/kotlin/internal/instruction/Mov.kt
- backend/shork/src/test/kotlin/instruction/TestMov.kt
> [#57] implement mov instruction

- backend/shork/src/main/kotlin/internal/instruction/Compare.kt
- backend/shork/src/test/kotlin/instruction/TestCompare.kt
> [#67] Implement CMP Instruction

- frontend/app/src/components/requireLogout/RequireLogout.test.tsx
- frontend/app/src/components/requireLogout/RequireLogout.tsx
- frontend/app/src/components/requireUser.tsx/RequireUser.test.tsx
- frontend/app/src/components/requireUser.tsx/RequireUser.tsx
- frontend/app/src/pages/landingPage/LandingPage.test.tsx
- frontend/app/src/pages/landingPage/LandingPage.tsx
- frontend/app/src/pages/playerCodeInput/PlayerCodingPage.tsx
- frontend/app/src/pages/playerSelection/PlayerSelection.test.tsx
- frontend/app/src/pages/playerSelection/PlayerSelection.tsx
- frontend/app/src/pages/waitingForResult/WaitingForResultPage.test.tsx
- frontend/app/src/pages/waitingForResult/WaitingForResultPage.tsx
- frontend/app/src/services/userContext/UserContextHelpers.ts
You can now use a RequireUser component to require a user in a page, or RequireLogout to require that a possibly logged in user, should be logged out
> 100 fe routing and usermanagement

- backend/shork/src/main/kotlin/internal/instruction/AbstractArithmeticInstruction.kt
- backend/shork/src/main/kotlin/internal/instruction/Add.kt
- backend/shork/src/main/kotlin/internal/instruction/Div.kt
- backend/shork/src/main/kotlin/internal/instruction/Mod.kt
- backend/shork/src/main/kotlin/internal/instruction/Mul.kt
- backend/shork/src/main/kotlin/internal/instruction/Sub.kt
- backend/shork/src/test/kotlin/instruction/TestAdd.kt
- backend/shork/src/test/kotlin/instruction/TestDiv.kt
- backend/shork/src/test/kotlin/instruction/TestMod.kt
- backend/shork/src/test/kotlin/instruction/TestMul.kt
- backend/shork/src/test/kotlin/instruction/TestSub.kt
Implement the ADD, SUB, MUL, DIV and MOD instructions.
> [#58, #59, #60, #61, #62] Implement arithmetic instructions

- .git-authors
- backend/api/src/main/kotlin/software/shonk/adapters/incoming/ShorkInterpreterController.kt
- backend/api/src/main/kotlin/software/shonk/application/port/incoming/ShorkUseCase.kt
- backend/api/src/main/kotlin/software/shonk/application/service/ShorkService.kt
- backend/api/src/main/kotlin/software/shonk/domain/Lobby.kt
- backend/api/src/test/kotlin/software/shonk/adapters/incoming/ShorkInterpreterControllerIT.kt
- backend/api/src/test/kotlin/software/shonk/application/service/ShorkServiceTest.kt
- backend/api/src/test/kotlin/software/shonk/domain/LobbyTest.kt
Lobby system is now implemented. Awaiting review from @0815Sailsman
> 101 implement lobby system in the backend

- backend/shork/src/main/kotlin/internal/instruction/Nop.kt
- backend/shork/src/test/kotlin/instruction/TestNop.kt
I ran into NOPs during development
Can't do anything about that now, though
_I'll see myself out_
> "Implement" NOP Instruction

- Containerfile
- backend/taskfile.yaml
Would be great if one of the reviewers could test on windows and then approve or comment what doesn't work :)
> Taskfile Windows Fix

- backend/api/src/main/kotlin/software/shonk/adapters/incoming/ShorkInterpreterController.kt
- backend/api/src/test/kotlin/software/shonk/adapters/incoming/ShorkInterpreterControllerV1IT.kt
PS. in my latest commit I meant to say endpoint instead of method
> [#113] added a new submit code method for apiv1 alongside its tests

- backend/shork/src/main/kotlin/internal/instruction/Sne.kt
- backend/shork/src/test/kotlin/instruction/TestSne.kt
I think one review would suffice (especially because this is basically as copy-pasted SEQ with `==` replaced by `!=`), but wanted to give both of you the opportunity.
I'm unsure about the X-Modifier being correct. Feedback from @PietHelzel on that would be appreciated
> [#132] implement sne instruction

- frontend/app/src/TestFactories.ts
- frontend/app/src/components/LobbySelection/LobbySelection.test.tsx
- frontend/app/src/components/LobbySelection/LobbySelection.tsx
- frontend/app/src/components/ui/table.tsx
- frontend/app/src/consts.ts
- frontend/app/src/domain/Lobby.ts
- frontend/app/src/main.tsx
- frontend/app/src/pages/lobbySelectionPage/LobbySelectionPage.test.tsx
- frontend/app/src/pages/lobbySelectionPage/LobbySelectionPage.tsx
- frontend/app/src/services/lobbyContext/LobbyContext.test.tsx
- frontend/app/src/services/lobbyContext/LobbyContext.tsx
- frontend/app/src/services/lobbyContext/LobbyContextHelpers.ts
- frontend/app/src/services/rest/RestService.ts
we decided to remove this feature branch and just do it directly into main. code in here has already been reviewed and should work like that.
> Rebase milestone-lobby branch into main

- backend/api/src/main/kotlin/software/shonk/application/service/V0ShorkService.kt
- backend/api/src/main/kotlin/software/shonk/domain/Lobby.kt
- backend/api/src/test/kotlin/software/shonk/domain/LobbyTest.kt
- backend/shork/src/main/kotlin/IShork.kt
- backend/shork/src/main/kotlin/MockShork.kt
- backend/shork/src/main/kotlin/Settings.kt
- backend/shork/src/main/kotlin/Shork.kt
- backend/shork/src/test/kotlin/TestSettings.kt
- backend/shork/src/test/kotlin/TestShork.kt
- backend/shork/src/test/kotlin/statistics/TestGameDataCollector.kt
> [#157] Make SHORK Settings respect initial instruction

- e2e/tests/fullUserflow.spec.ts
- frontend/app/src/TestFactories.ts
- frontend/app/src/assets/icon.svg
- frontend/app/src/pages/resultDisplayPage/ResultDisplayPage.test.tsx
- frontend/app/src/pages/resultDisplayPage/ResultDisplayPage.tsx
> 89 fix git

- backend/shork/src/main/kotlin/internal/compiler/Parser.kt
- backend/shork/src/test/kotlin/compiler/TestParser.kt
I just wanted to add a few more tests, it didn't seem like we had enough :point_right: :point_left:
> [#0] Add default modifier tests

- backend/api/build.gradle.kts
- backend/shork/build.gradle.kts
Closes #314 
Had to disable showing passed tests for the shork, because we have 24.000 and my laptop almost burned my apartment down when it ran with each one writing one line to stdout
> Fancy Junit Test output 

- api-v1.md
- architecture.drawio
> Modify API Spec to add a new endpoint that allows getting the lobby settings

- backend/api/src/main/kotlin/software/shonk/adapters/incoming/ShorkInterpreterController.kt
- backend/api/src/test/kotlin/software/shonk/adapters/incoming/ShorkInterpreterControllerV1IT.kt
Little changes needed so PR should be very quick.
> [#307] change get lobby status API response from 400 to 404 to match updated spec and adjust tests accordingly

- frontend/app/src/components/CodeEditor/CodeEditor.tsx
the regex checks if there are any unreadable characters in the file, tested it out with multiple files and works pretty well (without needing to install additional packages)
closes #154
> [#154] check if uploaded file contains unreadable characters

- backend/api/src/main/kotlin/software/shonk/adapters/incoming/ShorkInterpreterController.kt
- backend/api/src/main/kotlin/software/shonk/application/port/incoming/ShorkUseCase.kt
- backend/api/src/main/kotlin/software/shonk/application/service/ShorkService.kt
- backend/api/src/test/kotlin/software/shonk/adapters/incoming/ShorkInterpreterControllerV1IT.kt
- backend/api/src/test/kotlin/software/shonk/application/service/ShorkServiceTest.kt
> [#262] Prevent players from submitting code when they have not joined yet

- frontend/app/src/components/CodeEditor/CodeEditor.tsx
- frontend/app/src/components/CodeExampleCard/CodeExampleCard.test.tsx
- frontend/app/src/components/CodeExampleCard/CodeExampleCard.tsx
- frontend/app/src/components/ProgramInput/ProgramInput.tsx
- frontend/app/src/domain/CodeExample.ts
- frontend/app/src/lib/CodeExamples.ts
> 340 add code examples

- e2e/tests/fullUserflow.spec.ts
- frontend/app/src/pages/landingPage/LandingPage.module.css
- frontend/app/src/pages/landingPage/LandingPage.tsx
> Landing Page infodumps
